### ISSUE TITLE
Unbound variable when running the test_script.sh

### ISSUE THREAD

**Issue by viktorsmari** [thingful/decode-system-test#3]
```
./test_script.sh  create_stream
--> create a stream
./test_script.sh: line 16: $1: unbound variable
```

https://github.com/thingful/decode-system-test/blob/8553cf664db458c1005664c559623e6c9a8eb430/test_script.sh#L16

It also happens with 
`./test_script.sh  print`
`./test_script.sh: line 10: $1: unbound variable`

**Comment by viktorsmari** [comment]
Removing 'u' from `set -euo` removes the error, at least

**Comment by smulube** [comment]
Hi @viktorsmari - so sorry I haven't been noticing your comments here. This test script has actually been superseded by a simple web frontend that allows interacting with the components in a slightly easier way. I've just finished off an updated build of this web app, so when I push this, I will actually remove this script as it might confuse more than it helps.

Will close this issue once that updated application has been published, and I will push an update to this repo.
