### ISSUE TITLE
Why are we using a Makefile?

### ISSUE THREAD

**Issue by viktorsmari** [thingful/decode-system-test#5]
Is it not just adding a layer of complexity?

I personally prefer to use the `docker-compose` command, aliased as just `doco` :smile: 

When the readme tells me to use the `make` command, I have to read the Makefile and see what is does, thus, adding an extra layer. I also had to find out what `.PHONY` does in the Makefile :nerd_face:

**Comment by smulube** [comment]
heh, again I only added for my convenience out of habit as I put a Makefile in pretty much every project I do. 

Here it is so simple as to almost not be worthwhile, but our local convention is that we always just expect to be able to type `make start` in a project to start services locally (whatever that happens to mean), and in the actual code repositories to be able to run `make test` to run the test suite. Sometimes like here it is almost pointlessly minimal, but in other projects we have make doing things like building customized Dockerfiles or generating other dynamic artefacts before things can start

Again I'd be interested to know how you intend to use this repository as really its original purpose was just to demo the components.
